### PR TITLE
fix: generic_chain permissive blob gas

### LINKED ISSUE #947: Panic / failure handling some forks with `Cancun`
There's probably a more general framing of this issue, but wanted to report what I'm seeing so at least you are aware of this case. If forking e.g. `arbitrum`, on a contract that relies on some `Cancun` features, then you'll be required to specify `Cancun` in the hardfork history or else get `NotActivated` errors, which is fine/expected, except that if you do that, the fork starts panicking on `0.11.x`. You don't get a panic with `0.12.x`,  it just complains explicitly about missing `excess_gas_blobs` (not set), which I suppose is coming from `revm`. This is not meant to be a comprehensive patch, but I can confirm the following change allows at least some transactions to succeed:

```diff
modified   crates/edr_evm/src/spec.rs
@@ -293,7 +293,9 @@ impl BlockEnvConstructor<PartialHeader> for BlockEnv {
                 |BlobGas { excess_gas, .. }| {
                     eip4844::BlobExcessGasAndPrice::new(*excess_gas, hardfork >= l1::SpecId::PRAGUE)
                 },
-            ),
+            ).or_else(|| {
+                Some(eip4844::BlobExcessGasAndPrice::new(0u64, false))
+            }),
         }
     }
 }
@@ -318,7 +320,9 @@ impl BlockEnvConstructor<block::Header> for BlockEnv {
                 |BlobGas { excess_gas, .. }| {
                     eip4844::BlobExcessGasAndPrice::new(*excess_gas, hardfork >= l1::SpecId::PRAGUE)
                 },
-            ),
+            ).or_else(|| {
+                Some(eip4844::BlobExcessGasAndPrice::new(0u64, false))
+            }),
```

### PR DESCRIPTION
**Pull request by anaPerezGhiglia**
## Context
- Arbitrum chain does not fully comply with eip-4844. It is not exposing the blob gas information in block
- EDR's generic chain spec was requiring this field to be present above CANCUN update. 
- As a consequence, when building a block from Arbitrum chain, EDR would fail with `ExcessBlobGasNotSet` error

## Proposed solution
Modify the generic chain behavior so that it sets a default `BlobExcessGasAndPrice` of `0`  if the value is not provided by the block header

## Main changes
- Remove the `BlockEnvConstructor` restriction for `ChainSpec::BlockEnv` generic in the definition of `RuntimeSpec` trait. Instead define this restriction for a new `ChainSpec::BlockConstructor` type
  - The original restriction had as consequence that the way of constructing the Block depended on the `BlockEnv` type. 
  - The changes introduced in this PR makes it so that the definition for building a Block depends on the `ChainSpec` itself. 
  - The motivation of this change is that the `GenericChainSpec` defines the same `BlockEnv` type that the other chain specs. It didn't make much sense to define a new `BlockEnv` type for the generic chain spec when the type didn't need to change, just the way of building it.
 - Since `BlockConstructor` became something to be defined at a `ChainSpec` level, the trait had to be migrated to `evm_eth` crate
- Define a new `BlockEnvConstructor` implementation for `GenericChainSpec` that defines a default `BlobExcessGasAndPrice` value if t cannot be defined by block header.

### Side test changes
- created a new `integration::issues` module in `edr_generic` crate and moved existing issue-tests inside it.
- generalized & extracted the `get_chain_fork_provider` function helper.

closes #947

### CODE REVIEW

File: crates/edr_eth/src/spec.rs [hunk 1]
```diff
@@ -27,6 +27,14 @@ pub trait ChainSpec {
     type SignedTransaction: ExecutableTransaction
         + revm_context_interface::Transaction
         + TransactionValidation;
+    /// The chain's way of building blocks
+    type BlockConstructor: BlockEnvConstructor<crate::block::Header, Self::BlockEnv>;
+}
+
+/// A trait for constructing a (partial) block header into an EVM block.
+pub trait BlockEnvConstructor<HeaderT, BlockT: Block> {
```
Comment (Wodann) [inline crates/edr_eth/src/spec.rs:35]: I recommend making the `BlockT: Block` an associated type: `type BlockEnv: Block;` as it's constant per implementation of the trait (i.e. constant per ChainSpec).

File: crates/edr_generic/src/spec.rs [hunk 2]
```diff
@@ -37,6 +41,66 @@ impl ChainSpec for GenericChainSpec {
...
+            } else {
+                None
+            },
+            blob_excess_gas_and_price: header
+                .blob_gas
+                .as_ref()
+                .map(|BlobGas { excess_gas, .. }| {
+                    eip4844::BlobExcessGasAndPrice::new(*excess_gas, is_prague)
+                })
+                .or_else(|| Some(eip4844::BlobExcessGasAndPrice::new(0u64, is_prague))),
```
Comment (Wodann) [inline crates/edr_generic/src/spec.rs:101]: We should still check whether the `BlobExcessGasAndPrice` is required for this particular hardfork.

Could you also add a test that validates that we don't default the `BlobExcessGasAndPrice` for pre-Cancun hardforks? Similarly for L1

File: crates/edr_eth/src/spec.rs [hunk 3]
```diff
@@ -27,6 +27,14 @@ pub trait ChainSpec {
...
+    /// Converts the instance into an EVM block.
+    fn new_block_env(header: &HeaderT, hardfork: l1::SpecId) -> BlockT;
```
[the remark this answers is not in the document]
Comment (anaPerezGhiglia) [reply crates/edr_eth/src/spec.rs:37]: I see what you are suggesting. My first intuition was to have it separately so that the `L1BlockEnvConstructor ` could be reused in the `OpChainSpec` and avoid duplicating the logic of building the block. But I guess that repetition is accidental.
I will make the changes to remove the extra type and have each chain spec define its own building block logic. 
What I like of your proposal (and dislike of the current implementation) is that `edr_eth` knows nothing about this restriction

File: crates/edr_evm/src/spec.rs [hunk 4]
```diff
@@ -512,3 +462,130 @@ impl RuntimeSpec for L1ChainSpec {
...
+    #[test]
+    fn generic_block_constructor_should_not_default_excess_blob_gas_above_cancun() {
+        let header = build_block_header(None); // No blob gas information
+
+        let block = L1ChainSpec::new_block_env(&header, l1::SpecId::PRAGUE);
+        assert_eq!(block.blob_excess_gas_and_price, None);
+    }
+
+    #[test]
+    fn generic_block_constructor_should_use_existing_excess_blob_gas() {
```
Comment (Wodann) [inline crates/edr_evm/src/spec.rs:576]:
```suggestion
    fn l1_block_constructor_should_not_default_excess_blob_gas_for_cancun() {
        let header = build_block_header(None); // No blob gas information

        let block = L1ChainSpec::new_block_env(&header, l1::SpecId::CANCUN);
        assert_eq!(block.blob_excess_gas_and_price, None);
    }

    #[test]
    fn l1_block_constructor_should_not_default_excess_blob_gas_before_cancun() {
        let header = build_block_header(None); // No blob gas information

        let block = L1ChainSpec::new_block_env(&header, l1::SpecId::SHANGHAI);
        assert_eq!(block.blob_excess_gas_and_price, None);
    }

    #[test]
    fn l1_block_constructor_should_not_default_excess_blob_gas_after_cancun() {
        let header = build_block_header(None); // No blob gas information

        let block = L1ChainSpec::new_block_env(&header, l1::SpecId::PRAGUE);
        assert_eq!(block.blob_excess_gas_and_price, None);
    }

    #[test]
    fn l1_block_constructor_should_use_existing_excess_blob_gas() {
```

Should these all be named `l1_*`?

File: crates/edr_generic/src/spec.rs [hunk 5]
```diff
@@ -39,6 +43,72 @@ impl ChainSpec for GenericChainSpec {
     type SignedTransaction = crate::transaction::SignedWithFallbackToPostEip155;
 }
 
+impl GenericChainSpec {
+    fn blob_excess_gas_and_price(
```
Comment (Wodann) [inline crates/edr_generic/src/spec.rs:47]: This function doesn't require any types or member functions from `GenericChainSpec`, so it can be a free method:

```suggestion
fn blob_excess_gas_and_price(
```

File: crates/edr_generic/src/spec.rs [hunk 6]
```diff
@@ -191,3 +261,87 @@ impl<TimerT: Clone + TimeSinceEpoch> ProviderSpec<TimerT> for GenericChainSpec {
...
+
+        let block = GenericChainSpec::new_block_env(&header, l1::SpecId::CANCUN);
+        assert_eq!(
+            block.blob_excess_gas_and_price,
+            Some(eip4844::BlobExcessGasAndPrice::new(0u64, false))
+        );
+    }
+
+    #[test]
+    fn generic_block_constructor_should_default_excess_blob_gas_above_cancun() {
```
Comment (Wodann) [inline crates/edr_generic/src/spec.rs:313]:
```suggestion
    fn generic_block_constructor_should_default_excess_blob_gas_after_cancun() {
```

File: crates/edr_generic/src/spec.rs [hunk 7]
```diff
@@ -191,3 +261,87 @@ impl<TimerT: Clone + TimeSinceEpoch> ProviderSpec<TimerT> for GenericChainSpec {
...
+
+        let block = GenericChainSpec::new_block_env(&header, l1::SpecId::PRAGUE);
+        assert_eq!(
+            block.blob_excess_gas_and_price,
+            Some(eip4844::BlobExcessGasAndPrice::new(0u64, false))
+        );
+    }
+
+    #[test]
+    fn generic_block_constructor_should_nor_default_excess_blob_gas_below_cancun() {
```
Comment (Wodann) [inline crates/edr_generic/src/spec.rs:324]:
```suggestion
    fn generic_block_constructor_should_not_default_excess_blob_gas_before_cancun() {
```

File: crates/edr_generic/tests/integration/issues/issue_947.rs [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+
+    Ok(())
+}
+
+// `eth_debugTraceTransaction` should fail on l1 chain if
+// block header does not contain `excess_blob_gas` in Cancun or above
+// https://github.com/NomicFoundation/edr/issues/947
+#[serial]
+#[tokio::test(flavor = "multi_thread")]
+async fn issue_947_should_missing_blob_gas_fail_on_l1_above_cancun() -> anyhow::Result<()> {
```
Comment (Wodann) [inline crates/edr_generic/tests/integration/issues/issue_947.rs:90]:
```suggestion
async fn issue_947_should_fail_with_missing_blob_gas_fail_on_l1_after_cancun() -> anyhow::Result<()> {
```

File: crates/edr_generic/tests/integration/issues/issue_947.rs [hunk 9]
```diff
@@ -0,0 +1,135 @@
...
+
+    Ok(())
+}
+
+// `eth_debugTraceTransaction` should succeed on generic chain if
+// block header does not contain `excess_blob_gas` below Cancun
+// https://github.com/NomicFoundation/edr/issues/947
+#[serial]
+#[tokio::test(flavor = "multi_thread")]
+async fn issue_947_should_succeed_on_generic_pre_cancun() -> anyhow::Result<()> {
```
Comment (Wodann) [inline crates/edr_generic/tests/integration/issues/issue_947.rs:119]:
```suggestion
async fn issue_947_should_succeed_on_generic_before_cancun() -> anyhow::Result<()> {
```

File: crates/edr_op/src/spec.rs [hunk 10]
```diff
@@ -242,3 +246,131 @@ impl<TimerT: Clone + TimeSinceEpoch> ProviderSpec<TimerT> for OpChainSpec {
...
+            base_fee_per_gas: None,
+            withdrawals_root: None,
+            blob_gas,
+            parent_beacon_block_root: None,
+            requests_hash: Some(B256::random()),
+        }
+    }
+
+    #[test]
+    fn generic_block_constructor_should_not_default_excess_blob_gas_for_cancun() {
```
Comment (Wodann) [inline crates/edr_op/src/spec.rs:337]:
```suggestion
    fn op_block_constructor_should_not_default_excess_blob_gas_for_cancun() {
```

File: crates/edr_op/src/spec.rs [hunk 11]
```diff
@@ -242,3 +246,131 @@ impl<TimerT: Clone + TimeSinceEpoch> ProviderSpec<TimerT> for OpChainSpec {
...
+        let header = build_block_header(None); // No blob gas information
+
+        let block = OpChainSpec::new_block_env(&header, l1::SpecId::CANCUN);
+        assert_eq!(block.blob_excess_gas_and_price, None);
+    }
+
+    #[test]
+    fn generic_block_constructor_should_not_default_excess_blob_gas_below_cancun() {
```
Comment (Wodann) [inline crates/edr_op/src/spec.rs:345]:
```suggestion
    fn op_block_constructor_should_not_default_excess_blob_gas_before_cancun() {
```

File: crates/edr_op/src/spec.rs [hunk 12]
```diff
@@ -242,3 +246,131 @@ impl<TimerT: Clone + TimeSinceEpoch> ProviderSpec<TimerT> for OpChainSpec {
...
+        let header = build_block_header(None); // No blob gas information
+
+        let block = OpChainSpec::new_block_env(&header, l1::SpecId::SHANGHAI);
+        assert_eq!(block.blob_excess_gas_and_price, None);
+    }
+
+    #[test]
+    fn generic_block_constructor_should_not_default_excess_blob_gas_above_cancun() {
```
Comment (Wodann) [inline crates/edr_op/src/spec.rs:353]:
```suggestion
    fn op_block_constructor_should_not_default_excess_blob_gas_after_cancun() {
```

File: crates/edr_op/src/spec.rs [hunk 13]
```diff
@@ -242,3 +246,131 @@ impl<TimerT: Clone + TimeSinceEpoch> ProviderSpec<TimerT> for OpChainSpec {
...
+        let header = build_block_header(None); // No blob gas information
+
+        let block = OpChainSpec::new_block_env(&header, l1::SpecId::PRAGUE);
+        assert_eq!(block.blob_excess_gas_and_price, None);
+    }
+
+    #[test]
+    fn generic_block_constructor_should_use_existing_excess_blob_gas() {
```
Comment (Wodann) [inline crates/edr_op/src/spec.rs:361]:
```suggestion
    fn op_block_constructor_should_use_existing_excess_blob_gas() {
```

**Review by Wodann — CHANGES_REQUESTED** [review]
Apart from some typos, language clarification, and one other suggestion it looks good to me.

Could you please incorporate the suggested changes, if you agree. After that we can merge :)

File: crates/edr_evm/src/spec.rs (hunk 4 above)
Comment (anaPerezGhiglia) [reply crates/edr_evm/src/spec.rs:576]: indeed, thanks for the catch 🙇

**Comment by anaPerezGhiglia** [comment]
@nebasuke oh sorry, my bad! I wasn't sure how that works, and I didn't ask to clarify.
Do you think it's worth editing the [Release notes ](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.12.0-next.4) by hand this time to include it?

**Comment by anaPerezGhiglia** [comment]
@nebasuke [done](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.12.0-next.4). Please review the wording and let me know if there is something to change
